-- Schedule import: Gestalt intensive 19 Jun – 1 Jul 2026
-- Generated by: node scripts/generate-schedule-sql.mjs
-- Source: scanned 2024 schedule (dates shifted −1 day)

-- Update calendar dates on event days
UPDATE event_days SET event_date = '2026-06-19', is_rest_day = false WHERE day_index = 0;
UPDATE event_days SET event_date = '2026-06-20', is_rest_day = false WHERE day_index = 1;
UPDATE event_days SET event_date = '2026-06-21', is_rest_day = false WHERE day_index = 2;
UPDATE event_days SET event_date = '2026-06-22', is_rest_day = false WHERE day_index = 3;
UPDATE event_days SET event_date = '2026-06-23', is_rest_day = true WHERE day_index = 4;
UPDATE event_days SET event_date = '2026-06-24', is_rest_day = false WHERE day_index = 5;
UPDATE event_days SET event_date = '2026-06-25', is_rest_day = false WHERE day_index = 6;
UPDATE event_days SET event_date = '2026-06-26', is_rest_day = false WHERE day_index = 7;
UPDATE event_days SET event_date = '2026-06-27', is_rest_day = true WHERE day_index = 8;
UPDATE event_days SET event_date = '2026-06-28', is_rest_day = false WHERE day_index = 9;
UPDATE event_days SET event_date = '2026-06-29', is_rest_day = false WHERE day_index = 10;
UPDATE event_days SET event_date = '2026-06-30', is_rest_day = false WHERE day_index = 11;
UPDATE event_days SET event_date = '2026-07-01', is_rest_day = false WHERE day_index = 12;
UPDATE event_days SET label = 'Отъезд' WHERE day_index = 12;

-- Replace existing schedule (safe re-run after backup)
DELETE FROM event_audience WHERE event_id IN (SELECT id FROM schedule_events);
DELETE FROM schedule_events;

-- day_index 0 (2026-06-19)
WITH ins AS (
  INSERT INTO schedule_events (event_day_id, title, description, starts_at, ends_at, sort_order)
  SELECT ed.id, 'Регистрация участников', NULL, '2026-06-19T11:00:00+03:00'::timestamptz, '2026-06-19T17:00:00+03:00'::timestamptz, 1
  FROM event_days ed WHERE ed.day_index = 0
  RETURNING id
)
INSERT INTO event_audience (event_id, for_everyone)
SELECT id, true FROM ins;

WITH ins AS (
  INSERT INTO schedule_events (event_day_id, title, description, starts_at, ends_at, sort_order)
  SELECT ed.id, 'Обед', NULL, '2026-06-19T13:00:00+03:00'::timestamptz, '2026-06-19T14:00:00+03:00'::timestamptz, 2
  FROM event_days ed WHERE ed.day_index = 0
  RETURNING id
)
INSERT INTO event_audience (event_id, for_everyone)
SELECT id, true FROM ins;

WITH ins AS (
  INSERT INTO schedule_events (event_day_id, title, description, starts_at, ends_at, sort_order)
  SELECT ed.id, 'Собрание родителей и детей', NULL, '2026-06-19T17:40:00+03:00'::timestamptz, '2026-06-19T18:30:00+03:00'::timestamptz, 3
  FROM event_days ed WHERE ed.day_index = 0
  RETURNING id
)
INSERT INTO event_audience (event_id, for_everyone)
SELECT id, true FROM ins;

WITH ins AS (
  INSERT INTO schedule_events (event_day_id, title, description, starts_at, ends_at, sort_order)
  SELECT ed.id, 'Ужин', NULL, '2026-06-19T18:30:00+03:00'::timestamptz, '2026-06-19T19:30:00+03:00'::timestamptz, 4
  FROM event_days ed WHERE ed.day_index = 0
  RETURNING id
)
INSERT INTO event_audience (event_id, for_everyone)
SELECT id, true FROM ins;

WITH ins AS (
  INSERT INTO schedule_events (event_day_id, title, description, starts_at, ends_at, sort_order)
  SELECT ed.id, 'Открытие интенсива, распределение по группам', NULL, '2026-06-19T19:00:00+03:00'::timestamptz, '2026-06-19T20:30:00+03:00'::timestamptz, 5
  FROM event_days ed WHERE ed.day_index = 0
  RETURNING id
)
INSERT INTO event_audience (event_id, for_everyone)
SELECT id, true FROM ins;

-- day_index 1 (2026-06-20)
WITH ins AS (
  INSERT INTO schedule_events (event_day_id, title, description, starts_at, ends_at, sort_order)
  SELECT ed.id, 'Завтрак', NULL, '2026-06-20T08:30:00+03:00'::timestamptz, '2026-06-20T09:00:00+03:00'::timestamptz, 6
  FROM event_days ed WHERE ed.day_index = 1
  RETURNING id
)
INSERT INTO event_audience (event_id, for_everyone)
SELECT id, true FROM ins;

WITH ins AS (
  INSERT INTO schedule_events (event_day_id, title, description, starts_at, ends_at, sort_order)
  SELECT ed.id, 'Лекция. Распределение в пары терапевт-клиент, терапевт-супервизор. Выбор терапевтов подростками', NULL, '2026-06-20T09:30:00+03:00'::timestamptz, '2026-06-20T10:15:00+03:00'::timestamptz, 7
  FROM event_days ed WHERE ed.day_index = 1
  RETURNING id
)
INSERT INTO event_audience (event_id, for_everyone)
SELECT id, true FROM ins;

WITH ins AS (
  INSERT INTO schedule_events (event_day_id, title, description, starts_at, ends_at, sort_order)
  SELECT ed.id, 'Тематическая группа', NULL, '2026-06-20T10:30:00+03:00'::timestamptz, '2026-06-20T12:00:00+03:00'::timestamptz, 8
  FROM event_days ed WHERE ed.day_index = 1
  RETURNING id
)
INSERT INTO event_audience (event_id, for_everyone)
SELECT id, true FROM ins;

WITH ins AS (
  INSERT INTO schedule_events (event_day_id, title, description, starts_at, ends_at, sort_order)
  SELECT ed.id, 'Индивидуальная терапия', NULL, '2026-06-20T12:15:00+03:00'::timestamptz, '2026-06-20T12:55:00+03:00'::timestamptz, 9
  FROM event_days ed WHERE ed.day_index = 1
  RETURNING id
)
INSERT INTO event_audience (event_id, for_everyone)
SELECT id, true FROM ins;

WITH ins AS (
  INSERT INTO schedule_events (event_day_id, title, description, starts_at, ends_at, sort_order)
  SELECT ed.id, 'Супервизия', NULL, '2026-06-20T12:55:00+03:00'::timestamptz, '2026-06-20T13:15:00+03:00'::timestamptz, 10
  FROM event_days ed WHERE ed.day_index = 1
  RETURNING id
)
INSERT INTO event_audience (event_id, for_everyone)
SELECT id, true FROM ins;

WITH ins AS (
  INSERT INTO schedule_events (event_day_id, title, description, starts_at, ends_at, sort_order)
  SELECT ed.id, 'Обед', NULL, '2026-06-20T13:00:00+03:00'::timestamptz, '2026-06-20T14:00:00+03:00'::timestamptz, 11
  FROM event_days ed WHERE ed.day_index = 1
  RETURNING id
)
INSERT INTO event_audience (event_id, for_everyone)
SELECT id, true FROM ins;

WITH ins AS (
  INSERT INTO schedule_events (event_day_id, title, description, starts_at, ends_at, sort_order)
  SELECT ed.id, 'Индивидуальная терапия', 'Детские группы не работают', '2026-06-20T14:30:00+03:00'::timestamptz, '2026-06-20T15:10:00+03:00'::timestamptz, 12
  FROM event_days ed WHERE ed.day_index = 1
  RETURNING id
)
INSERT INTO event_audience (event_id, for_everyone)
SELECT id, true FROM ins;

WITH ins AS (
  INSERT INTO schedule_events (event_day_id, title, description, starts_at, ends_at, sort_order)
  SELECT ed.id, 'Супервизия', 'Детские группы не работают', '2026-06-20T15:10:00+03:00'::timestamptz, '2026-06-20T15:30:00+03:00'::timestamptz, 13
  FROM event_days ed WHERE ed.day_index = 1
  RETURNING id
)
INSERT INTO event_audience (event_id, for_everyone)
SELECT id, true FROM ins;

WITH ins AS (
  INSERT INTO schedule_events (event_day_id, title, description, starts_at, ends_at, sort_order)
  SELECT ed.id, 'Тематическая группа', NULL, '2026-06-20T15:50:00+03:00'::timestamptz, '2026-06-20T17:20:00+03:00'::timestamptz, 14
  FROM event_days ed WHERE ed.day_index = 1
  RETURNING id
)
INSERT INTO event_audience (event_id, for_everyone)
SELECT id, true FROM ins;

WITH ins AS (
  INSERT INTO schedule_events (event_day_id, title, description, starts_at, ends_at, sort_order)
  SELECT ed.id, 'Распределение на процесс-группы. Процесс-группа', NULL, '2026-06-20T17:40:00+03:00'::timestamptz, '2026-06-20T18:30:00+03:00'::timestamptz, 15
  FROM event_days ed WHERE ed.day_index = 1
  RETURNING id
)
INSERT INTO event_audience (event_id, for_everyone)
SELECT id, true FROM ins;

WITH ins AS (
  INSERT INTO schedule_events (event_day_id, title, description, starts_at, ends_at, sort_order)
  SELECT ed.id, 'Ужин', NULL, '2026-06-20T18:30:00+03:00'::timestamptz, '2026-06-20T19:30:00+03:00'::timestamptz, 16
  FROM event_days ed WHERE ed.day_index = 1
  RETURNING id
)
INSERT INTO event_audience (event_id, for_everyone)
SELECT id, true FROM ins;

-- day_index 2 (2026-06-21)
WITH ins AS (
  INSERT INTO schedule_events (event_day_id, title, description, starts_at, ends_at, sort_order)
  SELECT ed.id, 'Завтрак', NULL, '2026-06-21T08:30:00+03:00'::timestamptz, '2026-06-21T09:00:00+03:00'::timestamptz, 17
  FROM event_days ed WHERE ed.day_index = 2
  RETURNING id
)
INSERT INTO event_audience (event_id, for_everyone)
SELECT id, true FROM ins;

WITH ins AS (
  INSERT INTO schedule_events (event_day_id, title, description, starts_at, ends_at, sort_order)
  SELECT ed.id, 'Лекция', NULL, '2026-06-21T09:30:00+03:00'::timestamptz, '2026-06-21T10:15:00+03:00'::timestamptz, 18
  FROM event_days ed WHERE ed.day_index = 2
  RETURNING id
)
INSERT INTO event_audience (event_id, for_everyone)
SELECT id, true FROM ins;

WITH ins AS (
  INSERT INTO schedule_events (event_day_id, title, description, starts_at, ends_at, sort_order)
  SELECT ed.id, 'Тематическая группа', NULL, '2026-06-21T10:30:00+03:00'::timestamptz, '2026-06-21T12:00:00+03:00'::timestamptz, 19
  FROM event_days ed WHERE ed.day_index = 2
  RETURNING id
)
INSERT INTO event_audience (event_id, for_everyone)
SELECT id, true FROM ins;

WITH ins AS (
  INSERT INTO schedule_events (event_day_id, title, description, starts_at, ends_at, sort_order)
  SELECT ed.id, 'Индивидуальная терапия', NULL, '2026-06-21T12:15:00+03:00'::timestamptz, '2026-06-21T12:55:00+03:00'::timestamptz, 20
  FROM event_days ed WHERE ed.day_index = 2
  RETURNING id
)
INSERT INTO event_audience (event_id, for_everyone)
SELECT id, true FROM ins;

WITH ins AS (
  INSERT INTO schedule_events (event_day_id, title, description, starts_at, ends_at, sort_order)
  SELECT ed.id, 'Супервизия', NULL, '2026-06-21T12:55:00+03:00'::timestamptz, '2026-06-21T13:15:00+03:00'::timestamptz, 21
  FROM event_days ed WHERE ed.day_index = 2
  RETURNING id
)
INSERT INTO event_audience (event_id, for_everyone)
SELECT id, true FROM ins;

WITH ins AS (
  INSERT INTO schedule_events (event_day_id, title, description, starts_at, ends_at, sort_order)
  SELECT ed.id, 'Обед', NULL, '2026-06-21T13:00:00+03:00'::timestamptz, '2026-06-21T14:00:00+03:00'::timestamptz, 22
  FROM event_days ed WHERE ed.day_index = 2
  RETURNING id
)
INSERT INTO event_audience (event_id, for_everyone)
SELECT id, true FROM ins;

WITH ins AS (
  INSERT INTO schedule_events (event_day_id, title, description, starts_at, ends_at, sort_order)
  SELECT ed.id, 'Индивидуальная терапия', 'Детские группы не работают', '2026-06-21T14:30:00+03:00'::timestamptz, '2026-06-21T15:10:00+03:00'::timestamptz, 23
  FROM event_days ed WHERE ed.day_index = 2
  RETURNING id
)
INSERT INTO event_audience (event_id, for_everyone)
SELECT id, true FROM ins;

WITH ins AS (
  INSERT INTO schedule_events (event_day_id, title, description, starts_at, ends_at, sort_order)
  SELECT ed.id, 'Супервизия', 'Детские группы не работают', '2026-06-21T15:10:00+03:00'::timestamptz, '2026-06-21T15:30:00+03:00'::timestamptz, 24
  FROM event_days ed WHERE ed.day_index = 2
  RETURNING id
)
INSERT INTO event_audience (event_id, for_everyone)
SELECT id, true FROM ins;

WITH ins AS (
  INSERT INTO schedule_events (event_day_id, title, description, starts_at, ends_at, sort_order)
  SELECT ed.id, 'Тематическая группа', NULL, '2026-06-21T15:50:00+03:00'::timestamptz, '2026-06-21T17:20:00+03:00'::timestamptz, 25
  FROM event_days ed WHERE ed.day_index = 2
  RETURNING id
)
INSERT INTO event_audience (event_id, for_everyone)
SELECT id, true FROM ins;

WITH ins AS (
  INSERT INTO schedule_events (event_day_id, title, description, starts_at, ends_at, sort_order)
  SELECT ed.id, 'Процесс-группа', NULL, '2026-06-21T17:40:00+03:00'::timestamptz, '2026-06-21T18:30:00+03:00'::timestamptz, 26
  FROM event_days ed WHERE ed.day_index = 2
  RETURNING id
)
INSERT INTO event_audience (event_id, for_everyone)
SELECT id, true FROM ins;

WITH ins AS (
  INSERT INTO schedule_events (event_day_id, title, description, starts_at, ends_at, sort_order)
  SELECT ed.id, 'Ужин', NULL, '2026-06-21T18:30:00+03:00'::timestamptz, '2026-06-21T19:30:00+03:00'::timestamptz, 27
  FROM event_days ed WHERE ed.day_index = 2
  RETURNING id
)
INSERT INTO event_audience (event_id, for_everyone)
SELECT id, true FROM ins;

WITH ins AS (
  INSERT INTO schedule_events (event_day_id, title, description, starts_at, ends_at, sort_order)
  SELECT ed.id, 'Родительский клуб', 'Лекция / беседа для родителей', '2026-06-21T19:00:00+03:00'::timestamptz, '2026-06-21T19:30:00+03:00'::timestamptz, 28
  FROM event_days ed WHERE ed.day_index = 2
  RETURNING id
)
INSERT INTO event_audience (event_id, for_everyone)
SELECT id, true FROM ins;

WITH ins AS (
  INSERT INTO schedule_events (event_day_id, title, description, starts_at, ends_at, sort_order)
  SELECT ed.id, 'Встреча родителей с тренерами детских групп', NULL, '2026-06-21T19:30:00+03:00'::timestamptz, '2026-06-21T20:00:00+03:00'::timestamptz, 29
  FROM event_days ed WHERE ed.day_index = 2
  RETURNING id
)
INSERT INTO event_audience (event_id, for_everyone)
SELECT id, true FROM ins;

WITH ins AS (
  INSERT INTO schedule_events (event_day_id, title, description, starts_at, ends_at, sort_order)
  SELECT ed.id, 'Группа поддержки подростковых терапевтов', NULL, '2026-06-21T20:00:00+03:00'::timestamptz, '2026-06-21T21:00:00+03:00'::timestamptz, 30
  FROM event_days ed WHERE ed.day_index = 2
  RETURNING id
)
INSERT INTO event_audience (event_id, for_everyone)
SELECT id, true FROM ins;

-- day_index 3 (2026-06-22)
WITH ins AS (
  INSERT INTO schedule_events (event_day_id, title, description, starts_at, ends_at, sort_order)
  SELECT ed.id, 'Завтрак', NULL, '2026-06-22T08:30:00+03:00'::timestamptz, '2026-06-22T09:00:00+03:00'::timestamptz, 31
  FROM event_days ed WHERE ed.day_index = 3
  RETURNING id
)
INSERT INTO event_audience (event_id, for_everyone)
SELECT id, true FROM ins;

WITH ins AS (
  INSERT INTO schedule_events (event_day_id, title, description, starts_at, ends_at, sort_order)
  SELECT ed.id, 'Лекция', NULL, '2026-06-22T09:30:00+03:00'::timestamptz, '2026-06-22T10:15:00+03:00'::timestamptz, 32
  FROM event_days ed WHERE ed.day_index = 3
  RETURNING id
)
INSERT INTO event_audience (event_id, for_everyone)
SELECT id, true FROM ins;

WITH ins AS (
  INSERT INTO schedule_events (event_day_id, title, description, starts_at, ends_at, sort_order)
  SELECT ed.id, 'Тематическая группа', NULL, '2026-06-22T10:30:00+03:00'::timestamptz, '2026-06-22T12:00:00+03:00'::timestamptz, 33
  FROM event_days ed WHERE ed.day_index = 3
  RETURNING id
)
INSERT INTO event_audience (event_id, for_everyone)
SELECT id, true FROM ins;

WITH ins AS (
  INSERT INTO schedule_events (event_day_id, title, description, starts_at, ends_at, sort_order)
  SELECT ed.id, 'Индивидуальная терапия', NULL, '2026-06-22T12:15:00+03:00'::timestamptz, '2026-06-22T12:55:00+03:00'::timestamptz, 34
  FROM event_days ed WHERE ed.day_index = 3
  RETURNING id
)
INSERT INTO event_audience (event_id, for_everyone)
SELECT id, true FROM ins;

WITH ins AS (
  INSERT INTO schedule_events (event_day_id, title, description, starts_at, ends_at, sort_order)
  SELECT ed.id, 'Супервизия', NULL, '2026-06-22T12:55:00+03:00'::timestamptz, '2026-06-22T13:15:00+03:00'::timestamptz, 35
  FROM event_days ed WHERE ed.day_index = 3
  RETURNING id
)
INSERT INTO event_audience (event_id, for_everyone)
SELECT id, true FROM ins;

WITH ins AS (
  INSERT INTO schedule_events (event_day_id, title, description, starts_at, ends_at, sort_order)
  SELECT ed.id, 'Обед', NULL, '2026-06-22T13:00:00+03:00'::timestamptz, '2026-06-22T14:00:00+03:00'::timestamptz, 36
  FROM event_days ed WHERE ed.day_index = 3
  RETURNING id
)
INSERT INTO event_audience (event_id, for_everyone)
SELECT id, true FROM ins;

WITH ins AS (
  INSERT INTO schedule_events (event_day_id, title, description, starts_at, ends_at, sort_order)
  SELECT ed.id, 'Индивидуальная терапия', 'Детские группы не работают', '2026-06-22T14:30:00+03:00'::timestamptz, '2026-06-22T15:10:00+03:00'::timestamptz, 37
  FROM event_days ed WHERE ed.day_index = 3
  RETURNING id
)
INSERT INTO event_audience (event_id, for_everyone)
SELECT id, true FROM ins;

WITH ins AS (
  INSERT INTO schedule_events (event_day_id, title, description, starts_at, ends_at, sort_order)
  SELECT ed.id, 'Супервизия', 'Детские группы не работают', '2026-06-22T15:10:00+03:00'::timestamptz, '2026-06-22T15:30:00+03:00'::timestamptz, 38
  FROM event_days ed WHERE ed.day_index = 3
  RETURNING id
)
INSERT INTO event_audience (event_id, for_everyone)
SELECT id, true FROM ins;

WITH ins AS (
  INSERT INTO schedule_events (event_day_id, title, description, starts_at, ends_at, sort_order)
  SELECT ed.id, 'Тематическая группа', NULL, '2026-06-22T15:50:00+03:00'::timestamptz, '2026-06-22T17:20:00+03:00'::timestamptz, 39
  FROM event_days ed WHERE ed.day_index = 3
  RETURNING id
)
INSERT INTO event_audience (event_id, for_everyone)
SELECT id, true FROM ins;

WITH ins AS (
  INSERT INTO schedule_events (event_day_id, title, description, starts_at, ends_at, sort_order)
  SELECT ed.id, 'Процесс-группа', NULL, '2026-06-22T17:40:00+03:00'::timestamptz, '2026-06-22T18:30:00+03:00'::timestamptz, 40
  FROM event_days ed WHERE ed.day_index = 3
  RETURNING id
)
INSERT INTO event_audience (event_id, for_everyone)
SELECT id, true FROM ins;

WITH ins AS (
  INSERT INTO schedule_events (event_day_id, title, description, starts_at, ends_at, sort_order)
  SELECT ed.id, 'Ужин', NULL, '2026-06-22T18:30:00+03:00'::timestamptz, '2026-06-22T19:30:00+03:00'::timestamptz, 41
  FROM event_days ed WHERE ed.day_index = 3
  RETURNING id
)
INSERT INTO event_audience (event_id, for_everyone)
SELECT id, true FROM ins;

WITH ins AS (
  INSERT INTO schedule_events (event_day_id, title, description, starts_at, ends_at, sort_order)
  SELECT ed.id, 'Завершение трехдневки. Передача тренеров', NULL, '2026-06-22T19:00:00+03:00'::timestamptz, '2026-06-22T20:00:00+03:00'::timestamptz, 42
  FROM event_days ed WHERE ed.day_index = 3
  RETURNING id
)
INSERT INTO event_audience (event_id, for_everyone)
SELECT id, true FROM ins;

-- day_index 4 (2026-06-23)
WITH ins AS (
  INSERT INTO schedule_events (event_day_id, title, description, starts_at, ends_at, sort_order)
  SELECT ed.id, 'Выходной', 'Группы не работают', '2026-06-23T09:00:00+03:00'::timestamptz, '2026-06-23T18:00:00+03:00'::timestamptz, 43
  FROM event_days ed WHERE ed.day_index = 4
  RETURNING id
)
INSERT INTO event_audience (event_id, for_everyone)
SELECT id, true FROM ins;

-- day_index 5 (2026-06-24)
WITH ins AS (
  INSERT INTO schedule_events (event_day_id, title, description, starts_at, ends_at, sort_order)
  SELECT ed.id, 'Завтрак', NULL, '2026-06-24T08:30:00+03:00'::timestamptz, '2026-06-24T09:00:00+03:00'::timestamptz, 44
  FROM event_days ed WHERE ed.day_index = 5
  RETURNING id
)
INSERT INTO event_audience (event_id, for_everyone)
SELECT id, true FROM ins;

WITH ins AS (
  INSERT INTO schedule_events (event_day_id, title, description, starts_at, ends_at, sort_order)
  SELECT ed.id, 'Лекция', NULL, '2026-06-24T09:30:00+03:00'::timestamptz, '2026-06-24T10:15:00+03:00'::timestamptz, 45
  FROM event_days ed WHERE ed.day_index = 5
  RETURNING id
)
INSERT INTO event_audience (event_id, for_everyone)
SELECT id, true FROM ins;

WITH ins AS (
  INSERT INTO schedule_events (event_day_id, title, description, starts_at, ends_at, sort_order)
  SELECT ed.id, 'Тематическая группа', NULL, '2026-06-24T10:30:00+03:00'::timestamptz, '2026-06-24T12:00:00+03:00'::timestamptz, 46
  FROM event_days ed WHERE ed.day_index = 5
  RETURNING id
)
INSERT INTO event_audience (event_id, for_everyone)
SELECT id, true FROM ins;

WITH ins AS (
  INSERT INTO schedule_events (event_day_id, title, description, starts_at, ends_at, sort_order)
  SELECT ed.id, 'Индивидуальная терапия', NULL, '2026-06-24T12:15:00+03:00'::timestamptz, '2026-06-24T12:55:00+03:00'::timestamptz, 47
  FROM event_days ed WHERE ed.day_index = 5
  RETURNING id
)
INSERT INTO event_audience (event_id, for_everyone)
SELECT id, true FROM ins;

WITH ins AS (
  INSERT INTO schedule_events (event_day_id, title, description, starts_at, ends_at, sort_order)
  SELECT ed.id, 'Супервизия', NULL, '2026-06-24T12:55:00+03:00'::timestamptz, '2026-06-24T13:15:00+03:00'::timestamptz, 48
  FROM event_days ed WHERE ed.day_index = 5
  RETURNING id
)
INSERT INTO event_audience (event_id, for_everyone)
SELECT id, true FROM ins;

WITH ins AS (
  INSERT INTO schedule_events (event_day_id, title, description, starts_at, ends_at, sort_order)
  SELECT ed.id, 'Обед', NULL, '2026-06-24T13:00:00+03:00'::timestamptz, '2026-06-24T14:00:00+03:00'::timestamptz, 49
  FROM event_days ed WHERE ed.day_index = 5
  RETURNING id
)
INSERT INTO event_audience (event_id, for_everyone)
SELECT id, true FROM ins;

WITH ins AS (
  INSERT INTO schedule_events (event_day_id, title, description, starts_at, ends_at, sort_order)
  SELECT ed.id, 'Индивидуальная терапия', 'Детские группы не работают', '2026-06-24T14:30:00+03:00'::timestamptz, '2026-06-24T15:10:00+03:00'::timestamptz, 50
  FROM event_days ed WHERE ed.day_index = 5
  RETURNING id
)
INSERT INTO event_audience (event_id, for_everyone)
SELECT id, true FROM ins;

WITH ins AS (
  INSERT INTO schedule_events (event_day_id, title, description, starts_at, ends_at, sort_order)
  SELECT ed.id, 'Супервизия', 'Детские группы не работают', '2026-06-24T15:10:00+03:00'::timestamptz, '2026-06-24T15:30:00+03:00'::timestamptz, 51
  FROM event_days ed WHERE ed.day_index = 5
  RETURNING id
)
INSERT INTO event_audience (event_id, for_everyone)
SELECT id, true FROM ins;

WITH ins AS (
  INSERT INTO schedule_events (event_day_id, title, description, starts_at, ends_at, sort_order)
  SELECT ed.id, 'Тематическая группа', NULL, '2026-06-24T15:50:00+03:00'::timestamptz, '2026-06-24T17:20:00+03:00'::timestamptz, 52
  FROM event_days ed WHERE ed.day_index = 5
  RETURNING id
)
INSERT INTO event_audience (event_id, for_everyone)
SELECT id, true FROM ins;

WITH ins AS (
  INSERT INTO schedule_events (event_day_id, title, description, starts_at, ends_at, sort_order)
  SELECT ed.id, 'Процесс-группа', NULL, '2026-06-24T17:40:00+03:00'::timestamptz, '2026-06-24T18:30:00+03:00'::timestamptz, 53
  FROM event_days ed WHERE ed.day_index = 5
  RETURNING id
)
INSERT INTO event_audience (event_id, for_everyone)
SELECT id, true FROM ins;

WITH ins AS (
  INSERT INTO schedule_events (event_day_id, title, description, starts_at, ends_at, sort_order)
  SELECT ed.id, 'Ужин', NULL, '2026-06-24T18:30:00+03:00'::timestamptz, '2026-06-24T19:30:00+03:00'::timestamptz, 54
  FROM event_days ed WHERE ed.day_index = 5
  RETURNING id
)
INSERT INTO event_audience (event_id, for_everyone)
SELECT id, true FROM ins;

-- day_index 6 (2026-06-25)
WITH ins AS (
  INSERT INTO schedule_events (event_day_id, title, description, starts_at, ends_at, sort_order)
  SELECT ed.id, 'Завтрак', NULL, '2026-06-25T08:30:00+03:00'::timestamptz, '2026-06-25T09:00:00+03:00'::timestamptz, 55
  FROM event_days ed WHERE ed.day_index = 6
  RETURNING id
)
INSERT INTO event_audience (event_id, for_everyone)
SELECT id, true FROM ins;

WITH ins AS (
  INSERT INTO schedule_events (event_day_id, title, description, starts_at, ends_at, sort_order)
  SELECT ed.id, 'Лекция', NULL, '2026-06-25T09:30:00+03:00'::timestamptz, '2026-06-25T10:15:00+03:00'::timestamptz, 56
  FROM event_days ed WHERE ed.day_index = 6
  RETURNING id
)
INSERT INTO event_audience (event_id, for_everyone)
SELECT id, true FROM ins;

WITH ins AS (
  INSERT INTO schedule_events (event_day_id, title, description, starts_at, ends_at, sort_order)
  SELECT ed.id, 'Тематическая группа', NULL, '2026-06-25T10:30:00+03:00'::timestamptz, '2026-06-25T12:00:00+03:00'::timestamptz, 57
  FROM event_days ed WHERE ed.day_index = 6
  RETURNING id
)
INSERT INTO event_audience (event_id, for_everyone)
SELECT id, true FROM ins;

WITH ins AS (
  INSERT INTO schedule_events (event_day_id, title, description, starts_at, ends_at, sort_order)
  SELECT ed.id, 'Индивидуальная терапия', NULL, '2026-06-25T12:15:00+03:00'::timestamptz, '2026-06-25T12:55:00+03:00'::timestamptz, 58
  FROM event_days ed WHERE ed.day_index = 6
  RETURNING id
)
INSERT INTO event_audience (event_id, for_everyone)
SELECT id, true FROM ins;

WITH ins AS (
  INSERT INTO schedule_events (event_day_id, title, description, starts_at, ends_at, sort_order)
  SELECT ed.id, 'Супервизия', NULL, '2026-06-25T12:55:00+03:00'::timestamptz, '2026-06-25T13:15:00+03:00'::timestamptz, 59
  FROM event_days ed WHERE ed.day_index = 6
  RETURNING id
)
INSERT INTO event_audience (event_id, for_everyone)
SELECT id, true FROM ins;

WITH ins AS (
  INSERT INTO schedule_events (event_day_id, title, description, starts_at, ends_at, sort_order)
  SELECT ed.id, 'Обед', NULL, '2026-06-25T13:00:00+03:00'::timestamptz, '2026-06-25T14:00:00+03:00'::timestamptz, 60
  FROM event_days ed WHERE ed.day_index = 6
  RETURNING id
)
INSERT INTO event_audience (event_id, for_everyone)
SELECT id, true FROM ins;

WITH ins AS (
  INSERT INTO schedule_events (event_day_id, title, description, starts_at, ends_at, sort_order)
  SELECT ed.id, 'Индивидуальная терапия', 'Детские группы не работают', '2026-06-25T14:30:00+03:00'::timestamptz, '2026-06-25T15:10:00+03:00'::timestamptz, 61
  FROM event_days ed WHERE ed.day_index = 6
  RETURNING id
)
INSERT INTO event_audience (event_id, for_everyone)
SELECT id, true FROM ins;

WITH ins AS (
  INSERT INTO schedule_events (event_day_id, title, description, starts_at, ends_at, sort_order)
  SELECT ed.id, 'Супервизия', 'Детские группы не работают', '2026-06-25T15:10:00+03:00'::timestamptz, '2026-06-25T15:30:00+03:00'::timestamptz, 62
  FROM event_days ed WHERE ed.day_index = 6
  RETURNING id
)
INSERT INTO event_audience (event_id, for_everyone)
SELECT id, true FROM ins;

WITH ins AS (
  INSERT INTO schedule_events (event_day_id, title, description, starts_at, ends_at, sort_order)
  SELECT ed.id, 'Тематическая группа', NULL, '2026-06-25T15:50:00+03:00'::timestamptz, '2026-06-25T17:20:00+03:00'::timestamptz, 63
  FROM event_days ed WHERE ed.day_index = 6
  RETURNING id
)
INSERT INTO event_audience (event_id, for_everyone)
SELECT id, true FROM ins;

WITH ins AS (
  INSERT INTO schedule_events (event_day_id, title, description, starts_at, ends_at, sort_order)
  SELECT ed.id, 'Процесс-группа', NULL, '2026-06-25T17:40:00+03:00'::timestamptz, '2026-06-25T18:30:00+03:00'::timestamptz, 64
  FROM event_days ed WHERE ed.day_index = 6
  RETURNING id
)
INSERT INTO event_audience (event_id, for_everyone)
SELECT id, true FROM ins;

WITH ins AS (
  INSERT INTO schedule_events (event_day_id, title, description, starts_at, ends_at, sort_order)
  SELECT ed.id, 'Ужин', NULL, '2026-06-25T18:30:00+03:00'::timestamptz, '2026-06-25T19:30:00+03:00'::timestamptz, 65
  FROM event_days ed WHERE ed.day_index = 6
  RETURNING id
)
INSERT INTO event_audience (event_id, for_everyone)
SELECT id, true FROM ins;

WITH ins AS (
  INSERT INTO schedule_events (event_day_id, title, description, starts_at, ends_at, sort_order)
  SELECT ed.id, 'Родительский клуб', 'Лекция / беседа для родителей', '2026-06-25T19:00:00+03:00'::timestamptz, '2026-06-25T20:00:00+03:00'::timestamptz, 66
  FROM event_days ed WHERE ed.day_index = 6
  RETURNING id
)
INSERT INTO event_audience (event_id, for_everyone)
SELECT id, true FROM ins;

WITH ins AS (
  INSERT INTO schedule_events (event_day_id, title, description, starts_at, ends_at, sort_order)
  SELECT ed.id, 'Группа поддержки подростковых терапевтов', NULL, '2026-06-25T20:00:00+03:00'::timestamptz, '2026-06-25T21:00:00+03:00'::timestamptz, 67
  FROM event_days ed WHERE ed.day_index = 6
  RETURNING id
)
INSERT INTO event_audience (event_id, for_everyone)
SELECT id, true FROM ins;

-- day_index 7 (2026-06-26)
WITH ins AS (
  INSERT INTO schedule_events (event_day_id, title, description, starts_at, ends_at, sort_order)
  SELECT ed.id, 'Завтрак', NULL, '2026-06-26T08:30:00+03:00'::timestamptz, '2026-06-26T09:00:00+03:00'::timestamptz, 68
  FROM event_days ed WHERE ed.day_index = 7
  RETURNING id
)
INSERT INTO event_audience (event_id, for_everyone)
SELECT id, true FROM ins;

WITH ins AS (
  INSERT INTO schedule_events (event_day_id, title, description, starts_at, ends_at, sort_order)
  SELECT ed.id, 'Лекция', NULL, '2026-06-26T09:30:00+03:00'::timestamptz, '2026-06-26T10:15:00+03:00'::timestamptz, 69
  FROM event_days ed WHERE ed.day_index = 7
  RETURNING id
)
INSERT INTO event_audience (event_id, for_everyone)
SELECT id, true FROM ins;

WITH ins AS (
  INSERT INTO schedule_events (event_day_id, title, description, starts_at, ends_at, sort_order)
  SELECT ed.id, 'Тематическая группа', NULL, '2026-06-26T10:30:00+03:00'::timestamptz, '2026-06-26T12:00:00+03:00'::timestamptz, 70
  FROM event_days ed WHERE ed.day_index = 7
  RETURNING id
)
INSERT INTO event_audience (event_id, for_everyone)
SELECT id, true FROM ins;

WITH ins AS (
  INSERT INTO schedule_events (event_day_id, title, description, starts_at, ends_at, sort_order)
  SELECT ed.id, 'Индивидуальная терапия', NULL, '2026-06-26T12:15:00+03:00'::timestamptz, '2026-06-26T12:55:00+03:00'::timestamptz, 71
  FROM event_days ed WHERE ed.day_index = 7
  RETURNING id
)
INSERT INTO event_audience (event_id, for_everyone)
SELECT id, true FROM ins;

WITH ins AS (
  INSERT INTO schedule_events (event_day_id, title, description, starts_at, ends_at, sort_order)
  SELECT ed.id, 'Супервизия', NULL, '2026-06-26T12:55:00+03:00'::timestamptz, '2026-06-26T13:15:00+03:00'::timestamptz, 72
  FROM event_days ed WHERE ed.day_index = 7
  RETURNING id
)
INSERT INTO event_audience (event_id, for_everyone)
SELECT id, true FROM ins;

WITH ins AS (
  INSERT INTO schedule_events (event_day_id, title, description, starts_at, ends_at, sort_order)
  SELECT ed.id, 'Обед', NULL, '2026-06-26T13:00:00+03:00'::timestamptz, '2026-06-26T14:00:00+03:00'::timestamptz, 73
  FROM event_days ed WHERE ed.day_index = 7
  RETURNING id
)
INSERT INTO event_audience (event_id, for_everyone)
SELECT id, true FROM ins;

WITH ins AS (
  INSERT INTO schedule_events (event_day_id, title, description, starts_at, ends_at, sort_order)
  SELECT ed.id, 'Индивидуальная терапия', 'Детские группы не работают', '2026-06-26T14:30:00+03:00'::timestamptz, '2026-06-26T15:10:00+03:00'::timestamptz, 74
  FROM event_days ed WHERE ed.day_index = 7
  RETURNING id
)
INSERT INTO event_audience (event_id, for_everyone)
SELECT id, true FROM ins;

WITH ins AS (
  INSERT INTO schedule_events (event_day_id, title, description, starts_at, ends_at, sort_order)
  SELECT ed.id, 'Супервизия', 'Детские группы не работают', '2026-06-26T15:10:00+03:00'::timestamptz, '2026-06-26T15:30:00+03:00'::timestamptz, 75
  FROM event_days ed WHERE ed.day_index = 7
  RETURNING id
)
INSERT INTO event_audience (event_id, for_everyone)
SELECT id, true FROM ins;

WITH ins AS (
  INSERT INTO schedule_events (event_day_id, title, description, starts_at, ends_at, sort_order)
  SELECT ed.id, 'Тематическая группа', NULL, '2026-06-26T15:50:00+03:00'::timestamptz, '2026-06-26T17:20:00+03:00'::timestamptz, 76
  FROM event_days ed WHERE ed.day_index = 7
  RETURNING id
)
INSERT INTO event_audience (event_id, for_everyone)
SELECT id, true FROM ins;

WITH ins AS (
  INSERT INTO schedule_events (event_day_id, title, description, starts_at, ends_at, sort_order)
  SELECT ed.id, 'Процесс-группа', NULL, '2026-06-26T17:40:00+03:00'::timestamptz, '2026-06-26T18:30:00+03:00'::timestamptz, 77
  FROM event_days ed WHERE ed.day_index = 7
  RETURNING id
)
INSERT INTO event_audience (event_id, for_everyone)
SELECT id, true FROM ins;

WITH ins AS (
  INSERT INTO schedule_events (event_day_id, title, description, starts_at, ends_at, sort_order)
  SELECT ed.id, 'Ужин', NULL, '2026-06-26T18:30:00+03:00'::timestamptz, '2026-06-26T19:30:00+03:00'::timestamptz, 78
  FROM event_days ed WHERE ed.day_index = 7
  RETURNING id
)
INSERT INTO event_audience (event_id, for_everyone)
SELECT id, true FROM ins;

WITH ins AS (
  INSERT INTO schedule_events (event_day_id, title, description, starts_at, ends_at, sort_order)
  SELECT ed.id, 'Завершение трехдневки. Передача тренеров', NULL, '2026-06-26T19:00:00+03:00'::timestamptz, '2026-06-26T20:00:00+03:00'::timestamptz, 79
  FROM event_days ed WHERE ed.day_index = 7
  RETURNING id
)
INSERT INTO event_audience (event_id, for_everyone)
SELECT id, true FROM ins;

-- day_index 8 (2026-06-27)
WITH ins AS (
  INSERT INTO schedule_events (event_day_id, title, description, starts_at, ends_at, sort_order)
  SELECT ed.id, 'Выходной', 'Группы не работают', '2026-06-27T09:00:00+03:00'::timestamptz, '2026-06-27T18:00:00+03:00'::timestamptz, 80
  FROM event_days ed WHERE ed.day_index = 8
  RETURNING id
)
INSERT INTO event_audience (event_id, for_everyone)
SELECT id, true FROM ins;

-- day_index 9 (2026-06-28)
WITH ins AS (
  INSERT INTO schedule_events (event_day_id, title, description, starts_at, ends_at, sort_order)
  SELECT ed.id, 'Завтрак', NULL, '2026-06-28T08:30:00+03:00'::timestamptz, '2026-06-28T09:00:00+03:00'::timestamptz, 81
  FROM event_days ed WHERE ed.day_index = 9
  RETURNING id
)
INSERT INTO event_audience (event_id, for_everyone)
SELECT id, true FROM ins;

WITH ins AS (
  INSERT INTO schedule_events (event_day_id, title, description, starts_at, ends_at, sort_order)
  SELECT ed.id, 'Лекция', NULL, '2026-06-28T09:30:00+03:00'::timestamptz, '2026-06-28T10:15:00+03:00'::timestamptz, 82
  FROM event_days ed WHERE ed.day_index = 9
  RETURNING id
)
INSERT INTO event_audience (event_id, for_everyone)
SELECT id, true FROM ins;

WITH ins AS (
  INSERT INTO schedule_events (event_day_id, title, description, starts_at, ends_at, sort_order)
  SELECT ed.id, 'Тематическая группа', NULL, '2026-06-28T10:30:00+03:00'::timestamptz, '2026-06-28T12:00:00+03:00'::timestamptz, 83
  FROM event_days ed WHERE ed.day_index = 9
  RETURNING id
)
INSERT INTO event_audience (event_id, for_everyone)
SELECT id, true FROM ins;

WITH ins AS (
  INSERT INTO schedule_events (event_day_id, title, description, starts_at, ends_at, sort_order)
  SELECT ed.id, 'Индивидуальная терапия', NULL, '2026-06-28T12:15:00+03:00'::timestamptz, '2026-06-28T12:55:00+03:00'::timestamptz, 84
  FROM event_days ed WHERE ed.day_index = 9
  RETURNING id
)
INSERT INTO event_audience (event_id, for_everyone)
SELECT id, true FROM ins;

WITH ins AS (
  INSERT INTO schedule_events (event_day_id, title, description, starts_at, ends_at, sort_order)
  SELECT ed.id, 'Супервизия', NULL, '2026-06-28T12:55:00+03:00'::timestamptz, '2026-06-28T13:15:00+03:00'::timestamptz, 85
  FROM event_days ed WHERE ed.day_index = 9
  RETURNING id
)
INSERT INTO event_audience (event_id, for_everyone)
SELECT id, true FROM ins;

WITH ins AS (
  INSERT INTO schedule_events (event_day_id, title, description, starts_at, ends_at, sort_order)
  SELECT ed.id, 'Обед', NULL, '2026-06-28T13:00:00+03:00'::timestamptz, '2026-06-28T14:00:00+03:00'::timestamptz, 86
  FROM event_days ed WHERE ed.day_index = 9
  RETURNING id
)
INSERT INTO event_audience (event_id, for_everyone)
SELECT id, true FROM ins;

WITH ins AS (
  INSERT INTO schedule_events (event_day_id, title, description, starts_at, ends_at, sort_order)
  SELECT ed.id, 'Индивидуальная терапия', 'Детские группы не работают', '2026-06-28T14:30:00+03:00'::timestamptz, '2026-06-28T15:10:00+03:00'::timestamptz, 87
  FROM event_days ed WHERE ed.day_index = 9
  RETURNING id
)
INSERT INTO event_audience (event_id, for_everyone)
SELECT id, true FROM ins;

WITH ins AS (
  INSERT INTO schedule_events (event_day_id, title, description, starts_at, ends_at, sort_order)
  SELECT ed.id, 'Супервизия', 'Детские группы не работают', '2026-06-28T15:10:00+03:00'::timestamptz, '2026-06-28T15:30:00+03:00'::timestamptz, 88
  FROM event_days ed WHERE ed.day_index = 9
  RETURNING id
)
INSERT INTO event_audience (event_id, for_everyone)
SELECT id, true FROM ins;

WITH ins AS (
  INSERT INTO schedule_events (event_day_id, title, description, starts_at, ends_at, sort_order)
  SELECT ed.id, 'Тематическая группа', NULL, '2026-06-28T15:50:00+03:00'::timestamptz, '2026-06-28T17:20:00+03:00'::timestamptz, 89
  FROM event_days ed WHERE ed.day_index = 9
  RETURNING id
)
INSERT INTO event_audience (event_id, for_everyone)
SELECT id, true FROM ins;

WITH ins AS (
  INSERT INTO schedule_events (event_day_id, title, description, starts_at, ends_at, sort_order)
  SELECT ed.id, 'Процесс-группа', NULL, '2026-06-28T17:40:00+03:00'::timestamptz, '2026-06-28T18:30:00+03:00'::timestamptz, 90
  FROM event_days ed WHERE ed.day_index = 9
  RETURNING id
)
INSERT INTO event_audience (event_id, for_everyone)
SELECT id, true FROM ins;

WITH ins AS (
  INSERT INTO schedule_events (event_day_id, title, description, starts_at, ends_at, sort_order)
  SELECT ed.id, 'Ужин', NULL, '2026-06-28T18:30:00+03:00'::timestamptz, '2026-06-28T19:30:00+03:00'::timestamptz, 91
  FROM event_days ed WHERE ed.day_index = 9
  RETURNING id
)
INSERT INTO event_audience (event_id, for_everyone)
SELECT id, true FROM ins;

WITH ins AS (
  INSERT INTO schedule_events (event_day_id, title, description, starts_at, ends_at, sort_order)
  SELECT ed.id, 'Родительский клуб', 'Лекция / беседа для родителей', '2026-06-28T19:00:00+03:00'::timestamptz, '2026-06-28T20:30:00+03:00'::timestamptz, 92
  FROM event_days ed WHERE ed.day_index = 9
  RETURNING id
)
INSERT INTO event_audience (event_id, for_everyone)
SELECT id, true FROM ins;

-- day_index 10 (2026-06-29)
WITH ins AS (
  INSERT INTO schedule_events (event_day_id, title, description, starts_at, ends_at, sort_order)
  SELECT ed.id, 'Завтрак', NULL, '2026-06-29T08:30:00+03:00'::timestamptz, '2026-06-29T09:00:00+03:00'::timestamptz, 93
  FROM event_days ed WHERE ed.day_index = 10
  RETURNING id
)
INSERT INTO event_audience (event_id, for_everyone)
SELECT id, true FROM ins;

WITH ins AS (
  INSERT INTO schedule_events (event_day_id, title, description, starts_at, ends_at, sort_order)
  SELECT ed.id, 'Лекция', NULL, '2026-06-29T09:30:00+03:00'::timestamptz, '2026-06-29T10:15:00+03:00'::timestamptz, 94
  FROM event_days ed WHERE ed.day_index = 10
  RETURNING id
)
INSERT INTO event_audience (event_id, for_everyone)
SELECT id, true FROM ins;

WITH ins AS (
  INSERT INTO schedule_events (event_day_id, title, description, starts_at, ends_at, sort_order)
  SELECT ed.id, 'Тематическая группа', NULL, '2026-06-29T10:30:00+03:00'::timestamptz, '2026-06-29T12:00:00+03:00'::timestamptz, 95
  FROM event_days ed WHERE ed.day_index = 10
  RETURNING id
)
INSERT INTO event_audience (event_id, for_everyone)
SELECT id, true FROM ins;

WITH ins AS (
  INSERT INTO schedule_events (event_day_id, title, description, starts_at, ends_at, sort_order)
  SELECT ed.id, 'Индивидуальная терапия', NULL, '2026-06-29T12:15:00+03:00'::timestamptz, '2026-06-29T12:55:00+03:00'::timestamptz, 96
  FROM event_days ed WHERE ed.day_index = 10
  RETURNING id
)
INSERT INTO event_audience (event_id, for_everyone)
SELECT id, true FROM ins;

WITH ins AS (
  INSERT INTO schedule_events (event_day_id, title, description, starts_at, ends_at, sort_order)
  SELECT ed.id, 'Супервизия', NULL, '2026-06-29T12:55:00+03:00'::timestamptz, '2026-06-29T13:15:00+03:00'::timestamptz, 97
  FROM event_days ed WHERE ed.day_index = 10
  RETURNING id
)
INSERT INTO event_audience (event_id, for_everyone)
SELECT id, true FROM ins;

WITH ins AS (
  INSERT INTO schedule_events (event_day_id, title, description, starts_at, ends_at, sort_order)
  SELECT ed.id, 'Обед', NULL, '2026-06-29T13:00:00+03:00'::timestamptz, '2026-06-29T14:00:00+03:00'::timestamptz, 98
  FROM event_days ed WHERE ed.day_index = 10
  RETURNING id
)
INSERT INTO event_audience (event_id, for_everyone)
SELECT id, true FROM ins;

WITH ins AS (
  INSERT INTO schedule_events (event_day_id, title, description, starts_at, ends_at, sort_order)
  SELECT ed.id, 'Индивидуальная терапия', 'Детские группы не работают', '2026-06-29T14:30:00+03:00'::timestamptz, '2026-06-29T15:10:00+03:00'::timestamptz, 99
  FROM event_days ed WHERE ed.day_index = 10
  RETURNING id
)
INSERT INTO event_audience (event_id, for_everyone)
SELECT id, true FROM ins;

WITH ins AS (
  INSERT INTO schedule_events (event_day_id, title, description, starts_at, ends_at, sort_order)
  SELECT ed.id, 'Супервизия', 'Детские группы не работают', '2026-06-29T15:10:00+03:00'::timestamptz, '2026-06-29T15:30:00+03:00'::timestamptz, 100
  FROM event_days ed WHERE ed.day_index = 10
  RETURNING id
)
INSERT INTO event_audience (event_id, for_everyone)
SELECT id, true FROM ins;

WITH ins AS (
  INSERT INTO schedule_events (event_day_id, title, description, starts_at, ends_at, sort_order)
  SELECT ed.id, 'Тематическая группа', NULL, '2026-06-29T15:50:00+03:00'::timestamptz, '2026-06-29T17:20:00+03:00'::timestamptz, 101
  FROM event_days ed WHERE ed.day_index = 10
  RETURNING id
)
INSERT INTO event_audience (event_id, for_everyone)
SELECT id, true FROM ins;

WITH ins AS (
  INSERT INTO schedule_events (event_day_id, title, description, starts_at, ends_at, sort_order)
  SELECT ed.id, 'Процесс-группа', NULL, '2026-06-29T17:40:00+03:00'::timestamptz, '2026-06-29T18:30:00+03:00'::timestamptz, 102
  FROM event_days ed WHERE ed.day_index = 10
  RETURNING id
)
INSERT INTO event_audience (event_id, for_everyone)
SELECT id, true FROM ins;

WITH ins AS (
  INSERT INTO schedule_events (event_day_id, title, description, starts_at, ends_at, sort_order)
  SELECT ed.id, 'Ужин', NULL, '2026-06-29T18:30:00+03:00'::timestamptz, '2026-06-29T19:30:00+03:00'::timestamptz, 103
  FROM event_days ed WHERE ed.day_index = 10
  RETURNING id
)
INSERT INTO event_audience (event_id, for_everyone)
SELECT id, true FROM ins;

WITH ins AS (
  INSERT INTO schedule_events (event_day_id, title, description, starts_at, ends_at, sort_order)
  SELECT ed.id, 'Встреча родителей с тренерами детских групп', NULL, '2026-06-29T19:00:00+03:00'::timestamptz, '2026-06-29T20:00:00+03:00'::timestamptz, 104
  FROM event_days ed WHERE ed.day_index = 10
  RETURNING id
)
INSERT INTO event_audience (event_id, for_everyone)
SELECT id, true FROM ins;

WITH ins AS (
  INSERT INTO schedule_events (event_day_id, title, description, starts_at, ends_at, sort_order)
  SELECT ed.id, 'Группа поддержки подростковых терапевтов', NULL, '2026-06-29T20:00:00+03:00'::timestamptz, '2026-06-29T21:00:00+03:00'::timestamptz, 105
  FROM event_days ed WHERE ed.day_index = 10
  RETURNING id
)
INSERT INTO event_audience (event_id, for_everyone)
SELECT id, true FROM ins;

-- day_index 11 (2026-06-30)
WITH ins AS (
  INSERT INTO schedule_events (event_day_id, title, description, starts_at, ends_at, sort_order)
  SELECT ed.id, 'Завтрак', NULL, '2026-06-30T08:30:00+03:00'::timestamptz, '2026-06-30T09:00:00+03:00'::timestamptz, 106
  FROM event_days ed WHERE ed.day_index = 11
  RETURNING id
)
INSERT INTO event_audience (event_id, for_everyone)
SELECT id, true FROM ins;

WITH ins AS (
  INSERT INTO schedule_events (event_day_id, title, description, starts_at, ends_at, sort_order)
  SELECT ed.id, 'Лекция', NULL, '2026-06-30T09:30:00+03:00'::timestamptz, '2026-06-30T10:15:00+03:00'::timestamptz, 107
  FROM event_days ed WHERE ed.day_index = 11
  RETURNING id
)
INSERT INTO event_audience (event_id, for_everyone)
SELECT id, true FROM ins;

WITH ins AS (
  INSERT INTO schedule_events (event_day_id, title, description, starts_at, ends_at, sort_order)
  SELECT ed.id, 'Тематическая группа', NULL, '2026-06-30T10:30:00+03:00'::timestamptz, '2026-06-30T12:00:00+03:00'::timestamptz, 108
  FROM event_days ed WHERE ed.day_index = 11
  RETURNING id
)
INSERT INTO event_audience (event_id, for_everyone)
SELECT id, true FROM ins;

WITH ins AS (
  INSERT INTO schedule_events (event_day_id, title, description, starts_at, ends_at, sort_order)
  SELECT ed.id, 'Индивидуальная терапия', NULL, '2026-06-30T12:15:00+03:00'::timestamptz, '2026-06-30T12:55:00+03:00'::timestamptz, 109
  FROM event_days ed WHERE ed.day_index = 11
  RETURNING id
)
INSERT INTO event_audience (event_id, for_everyone)
SELECT id, true FROM ins;

WITH ins AS (
  INSERT INTO schedule_events (event_day_id, title, description, starts_at, ends_at, sort_order)
  SELECT ed.id, 'Супервизия', NULL, '2026-06-30T12:55:00+03:00'::timestamptz, '2026-06-30T13:15:00+03:00'::timestamptz, 110
  FROM event_days ed WHERE ed.day_index = 11
  RETURNING id
)
INSERT INTO event_audience (event_id, for_everyone)
SELECT id, true FROM ins;

WITH ins AS (
  INSERT INTO schedule_events (event_day_id, title, description, starts_at, ends_at, sort_order)
  SELECT ed.id, 'Обед', NULL, '2026-06-30T13:00:00+03:00'::timestamptz, '2026-06-30T14:00:00+03:00'::timestamptz, 111
  FROM event_days ed WHERE ed.day_index = 11
  RETURNING id
)
INSERT INTO event_audience (event_id, for_everyone)
SELECT id, true FROM ins;

WITH ins AS (
  INSERT INTO schedule_events (event_day_id, title, description, starts_at, ends_at, sort_order)
  SELECT ed.id, 'Индивидуальная терапия', 'Детские группы не работают', '2026-06-30T14:30:00+03:00'::timestamptz, '2026-06-30T15:10:00+03:00'::timestamptz, 112
  FROM event_days ed WHERE ed.day_index = 11
  RETURNING id
)
INSERT INTO event_audience (event_id, for_everyone)
SELECT id, true FROM ins;

WITH ins AS (
  INSERT INTO schedule_events (event_day_id, title, description, starts_at, ends_at, sort_order)
  SELECT ed.id, 'Супервизия', 'Детские группы не работают', '2026-06-30T15:10:00+03:00'::timestamptz, '2026-06-30T15:30:00+03:00'::timestamptz, 113
  FROM event_days ed WHERE ed.day_index = 11
  RETURNING id
)
INSERT INTO event_audience (event_id, for_everyone)
SELECT id, true FROM ins;

WITH ins AS (
  INSERT INTO schedule_events (event_day_id, title, description, starts_at, ends_at, sort_order)
  SELECT ed.id, 'Тематическая группа', NULL, '2026-06-30T15:50:00+03:00'::timestamptz, '2026-06-30T17:20:00+03:00'::timestamptz, 114
  FROM event_days ed WHERE ed.day_index = 11
  RETURNING id
)
INSERT INTO event_audience (event_id, for_everyone)
SELECT id, true FROM ins;

WITH ins AS (
  INSERT INTO schedule_events (event_day_id, title, description, starts_at, ends_at, sort_order)
  SELECT ed.id, 'Процесс-группа', NULL, '2026-06-30T17:40:00+03:00'::timestamptz, '2026-06-30T18:30:00+03:00'::timestamptz, 115
  FROM event_days ed WHERE ed.day_index = 11
  RETURNING id
)
INSERT INTO event_audience (event_id, for_everyone)
SELECT id, true FROM ins;

WITH ins AS (
  INSERT INTO schedule_events (event_day_id, title, description, starts_at, ends_at, sort_order)
  SELECT ed.id, 'Ужин', NULL, '2026-06-30T18:30:00+03:00'::timestamptz, '2026-06-30T19:30:00+03:00'::timestamptz, 116
  FROM event_days ed WHERE ed.day_index = 11
  RETURNING id
)
INSERT INTO event_audience (event_id, for_everyone)
SELECT id, true FROM ins;

WITH ins AS (
  INSERT INTO schedule_events (event_day_id, title, description, starts_at, ends_at, sort_order)
  SELECT ed.id, 'Завершение интенсива', NULL, '2026-06-30T19:00:00+03:00'::timestamptz, '2026-06-30T20:30:00+03:00'::timestamptz, 117
  FROM event_days ed WHERE ed.day_index = 11
  RETURNING id
)
INSERT INTO event_audience (event_id, for_everyone)
SELECT id, true FROM ins;

-- day_index 12 (2026-07-01)
WITH ins AS (
  INSERT INTO schedule_events (event_day_id, title, description, starts_at, ends_at, sort_order)
  SELECT ed.id, 'Отъезд', 'До 08:30', '2026-07-01T06:00:00+03:00'::timestamptz, '2026-07-01T08:30:00+03:00'::timestamptz, 118
  FROM event_days ed WHERE ed.day_index = 12
  RETURNING id
)
INSERT INTO event_audience (event_id, for_everyone)
SELECT id, true FROM ins;
